---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: team-projekt-kkk-keycloak
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
