---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: team-projekt-kkk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-projekt-kkk-frontend
  template:
    metadata:
      labels:
        app: team-projekt-kkk-frontend
    spec:
      containers:
        - name: frontend
          image: underwoodsteam/prod-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend-service:5000"
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.4.6
          args: ['start-dev']
          user: root
          ports:
            - containerPort: 8080
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: keycloak-persistent-storage
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-persistent-storage
          persistentVolumeClaim:
            claimName: keycloak-pvc
