---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: team-projekt-kkk-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-projekt-kkk-frontend
  template:
    metadata:
      labels:
        app: team-projekt-kkk-frontend
    spec:
      containers:
        - name: frontend
          image: underwoodsteam/prod-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend-service:5000"
