---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: team-projekt-kkk-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
